### ISSUE TITLE
Package Installer- ERROR com.percussion.deployer.objectstore.PSArchive - null C:com.percussion.deployer.objectstore.PSArchiveDetail:L:263 appeared on selecting the Package File created with the help of Package Builder.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#537]
1. Launch Package Builder and connect to the CMS server.
2. Click on New button.
![image](https://user-images.githubusercontent.com/77011198/158345003-ab4203e8-7dbb-48cf-a00f-2bcc1cf9e765.png)
3. Enter data for required field and click on Save button.
![image](https://user-images.githubusercontent.com/77011198/158345295-2105b3fc-a23a-4636-935c-09cfab189b1c.png)

4. Click on Home button.
![image](https://user-images.githubusercontent.com/77011198/158345374-3b8e3908-ea6a-4209-99be-0a65c9ef25d6.png)
5. Select the package and click on Build button.
![image](https://user-images.githubusercontent.com/77011198/158345474-9cb50a19-2027-4a39-8b3c-ec80df2d6333.png)

6. Select the Target directory and click on Ok button.
![image](https://user-images.githubusercontent.com/77011198/158345594-42fca9cb-e40f-4f26-a6c9-3c2d08c2b9ef.png)
![image](https://user-images.githubusercontent.com/77011198/158345642-604076a0-b89e-4d70-b34d-49c39f4320fc.png)
7. Now launch the Package Installer.
8. Select the Package file created in above step and observe the error appeared on Package Information.
![image](https://user-images.githubusercontent.com/77011198/158345852-5b7cebc9-a026-4397-8990-a1ed6c9dd25a.png)
9. Observe the error logged on console.
![image](https://user-images.githubusercontent.com/77011198/158346002-ad9b2dee-ff51-4275-a3ab-1a3b470c4b45.png)

**Comment by natechadwick** [comment]
@Yashdeep2001  can you confirm that this is resolved?

**Comment by natechadwick** [comment]
Closing issue. If it tests ok, please remove the Ready for QA label. If there is still a problem, please re-open and remove the Ready For QA label - label - Re-Opened.

**Comment by Yashdeep2001** [comment]
Still showing invalid and this error is present on console
![image](https://user-images.githubusercontent.com/103224298/190244700-a40db5c5-9413-48b6-9e59-18302b71b44e.png)

**Comment by natechadwick** [comment]
@Yashdeep2001  Are you sure that package is valid?

**Comment by Yashdeep2001** [comment]
![image](https://user-images.githubusercontent.com/103224298/190263447-b9d709e5-72f4-40df-a15f-1715cd6cea51.png)
![image](https://user-images.githubusercontent.com/103224298/190263481-594948f8-2f76-4ea8-b63b-75795d65cdb9.png)
package succesfully installing if package is valid.
