### ISSUE TITLE
When configuring SFTP for publishing, there are inconsistencies in the Publishing configuration dialog box

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#600]
I attempted to configure publishing to a SFTP location.  There are a few things on the dialog box that do not appear to be working correctly.  

1)  The authentication choice (Password or Private key) radio button does not seem to be "sticky".  If I select Private Key, it goes away if I go back into the dialog box.  
Before:
![image](https://user-images.githubusercontent.com/50147765/184655613-34bc4010-96ab-452d-812b-2fe4c979b654.png)

During:
![image](https://user-images.githubusercontent.com/50147765/184655722-786a9065-a3c6-465e-965e-eaa065bc021a.png)

After:  
![image](https://user-images.githubusercontent.com/50147765/184655847-401ef62c-2c90-4573-8c48-a0bca94709f3.png)

When I select Private Key option - The Password boxes should be "greyed" out or disabled.  That is not happening:
![image](https://user-images.githubusercontent.com/50147765/184656013-bca15022-6f17-40d4-8f5d-304195fe74e9.png)

Also, when I click Private Key - I should have the ability to use the dropdown to select the key.pem file that is the the rxconfig\ssh-keys folder.  Below is a screenshot of the folder structure and the dialog is picking up the config file, but not the key.

![image](https://user-images.githubusercontent.com/50147765/184656247-09ecbf04-1d27-457f-acc6-b7682373f044.png)

When I go into the Publishing Config dialog box, nothing happens when I select the drop-down selector.
![image](https://user-images.githubusercontent.com/50147765/184656396-561c9e42-b38f-4318-a137-94da0e12e588.png)

Publishing fails with the configuration that I have with no error other than - Cannot connect to publishing server.
![image](https://user-images.githubusercontent.com/50147765/184656583-c799295e-b03a-4a85-9d13-973dfde15d03.png)

The failure COULD? be related to one of the properties above not being properly set.

**Comment by natechadwick** [comment]
@NxPerc2019 This should be fixed so it defaults to private key option on new configuration and enables / disabled password and key list based on the selection.  The sshd config file is also no longer included in the list of keys.

**Comment by NxPerc2019** [comment]
I retested this with the nightly build of 8.1.1 below:
![image](https://user-images.githubusercontent.com/50147765/185171533-60c5f8b5-70ca-4451-a87e-0b8a943b50c0.png)

There are still 2 issues that are appearing.

1.  "Private key" is not being selected as default when the driver type SFTP is selected:
![image](https://user-images.githubusercontent.com/50147765/185171876-108c641e-0814-4531-98f1-fafee5cb7581.png)

2.  When I have "Private key" enabled, I still cannot select the key.pem file from the dropdown.
![image](https://user-images.githubusercontent.com/50147765/185172245-b2acec70-b843-4caf-8a8d-86a1843cc59f.png)
![image](https://user-images.githubusercontent.com/50147765/185172386-5fa3609a-6045-4c38-a1e3-99a4e241a8e1.png)

I restarted CMS and DTS after putting the key.pem file into the rxconfig\ssh-keys directory  and it does not appear.

**Comment by NxPerc2019** [comment]
I retested this on the following nightly build:
![image](https://user-images.githubusercontent.com/50147765/185698837-66b46732-662f-4756-883c-4460487958fc.png)

I am still unable to select the key.pem file in the Publishing Dialog box.  I attempted to publish anyway and it still is looking for the config file.  Attached is the server log.
[server.log](https://github.com/percussion/percussioncms/files/9385057/server.log)

**Comment by Yashdeep2001** [comment]
Password is now getting greyed out.

![image](https://user-images.githubusercontent.com/103224298/187220752-2f993f26-f3fe-4290-93b0-3f5d48a65310.png)

However the dropdown is not showing the config or the key file which is present in rxconfig/ssh.keys

![image](https://user-images.githubusercontent.com/103224298/187221448-71a2a029-e217-4abc-8edc-a14089e6ebee.png)

![image](https://user-images.githubusercontent.com/103224298/187221787-efa52ebd-b227-452f-bd7a-69aa4a5c3184.png)

**Comment by natechadwick** [comment]
Closing issue.  Please re-open if tested and have issues.  If it is all set remove the Ready for QA flag.
